const fs = require('fs');
let code = fs.readFileSync('src/components/Layout.tsx', 'utf-8');

// Update desktop nav
code = code.replace(
  `<button onClick={() => handleScrollTo('visas')} className="hover:text-gold-500 transition-colors">Visas</button>\n            <button onClick={() => handleScrollTo('services')} className="hover:text-gold-500 transition-colors">Services</button>\n            <button onClick={() => handleScrollTo('jobs')} className="hover:text-gold-500 transition-colors">Jobs</button>\n            <button onClick={() => handleScrollTo('partners')} className="hover:text-gold-500 transition-colors">Partners</button>\n            <button onClick={() => handleScrollTo('about')} className="hover:text-gold-500 transition-colors">About Us</button>\n            <button onClick={() => handleScrollTo('contact')} className="hover:text-gold-500 transition-colors">Contact Us</button>`,
  `<button onClick={() => onNavigate('home')} className="hover:text-gold-500 transition-colors">Opportunities</button>\n            <button onClick={() => onNavigate('candidate-portal')} className="hover:text-gold-500 transition-colors">For Talent</button>\n            <button onClick={() => onNavigate('employer-portal')} className="hover:text-gold-500 transition-colors">For Employers</button>\n            <button onClick={() => handleScrollTo('about')} className="hover:text-gold-500 transition-colors">About</button>\n            <button onClick={() => handleScrollTo('contact')} className="hover:text-gold-500 transition-colors">Insights</button>`
);

// Update mobile nav
code = code.replace(
  `<button onClick={() => { handleScrollTo('visas'); setMobileMenuOpen(false); }} className="text-left text-2xl font-display italic font-bold tracking-wider hover:text-gold-500 text-white">Visas</button>\n                <button onClick={() => { handleScrollTo('services'); setMobileMenuOpen(false); }} className="text-left text-2xl font-display italic font-bold tracking-wider hover:text-gold-500 text-white">Services</button>\n                <button onClick={() => { handleScrollTo('jobs'); setMobileMenuOpen(false); }} className="text-left text-2xl font-display italic font-bold tracking-wider hover:text-gold-500 text-white">Jobs</button>\n                <button onClick={() => { handleScrollTo('partners'); setMobileMenuOpen(false); }} className="text-left text-2xl font-display italic font-bold tracking-wider hover:text-gold-500 text-white">Partners</button>\n                <button onClick={() => { handleScrollTo('about'); setMobileMenuOpen(false); }} className="text-left text-2xl font-display italic font-bold tracking-wider hover:text-gold-500 text-white">About Us</button>\n                <button onClick={() => { handleScrollTo('contact'); setMobileMenuOpen(false); }} className="text-left text-2xl font-display italic font-bold tracking-wider hover:text-gold-500 text-white">Contact Us</button>`,
  `<button onClick={() => { onNavigate('home'); setMobileMenuOpen(false); }} className="text-left text-2xl font-display italic font-bold tracking-wider hover:text-gold-500 text-white">Opportunities</button>\n                <button onClick={() => { onNavigate('candidate-portal'); setMobileMenuOpen(false); }} className="text-left text-2xl font-display italic font-bold tracking-wider hover:text-gold-500 text-white">For Talent</button>\n                <button onClick={() => { onNavigate('employer-portal'); setMobileMenuOpen(false); }} className="text-left text-2xl font-display italic font-bold tracking-wider hover:text-gold-500 text-white">For Employers</button>\n                <button onClick={() => { handleScrollTo('about'); setMobileMenuOpen(false); }} className="text-left text-2xl font-display italic font-bold tracking-wider hover:text-gold-500 text-white">About</button>\n                <button onClick={() => { handleScrollTo('contact'); setMobileMenuOpen(false); }} className="text-left text-2xl font-display italic font-bold tracking-wider hover:text-gold-500 text-white">Insights</button>`
);

fs.writeFileSync('src/components/Layout.tsx', code);
